In [4]:
my_list = [1,2,3]

In [5]:
my_list

[1, 2, 3]

In [6]:
import numpy as np

In [7]:
arr = np.array(my_list)

In [8]:
arr

array([1, 2, 3])

In [9]:
my_mat = [[1,2,3], [4,5,6], [7,8,9]]

In [10]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
new_arr = np.array(my_mat)

In [12]:
new_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [15]:
np.zeros(3)

array([0., 0., 0.])

In [17]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## linspace retorna números igualmente espaçados um do outro, começando no 1º argumento até o 2º argumento. 3º argumento é o número de elementos.

In [20]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [21]:
np.linspace(0,10, 10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

## criar uma matriz identidade

In [22]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
np.random.rand(5)

array([0.9740975 , 0.05918413, 0.58352325, 0.29785903, 0.59354714])

In [25]:
np.random.randn(4,4)

array([[ 1.15482084, -0.20733341, -0.67378998, -0.56788363],
       [ 0.71350213,  1.02374224,  1.17188063, -0.17881427],
       [-1.43161428,  2.3709776 , -1.12411159, -0.86826266],
       [-1.49766818, -0.3614488 , -0.33976642, -1.0923915 ]])

In [27]:
np.random.randint(-5,5,10)

array([-2, -4,  1,  1, -3, -5, -5,  0, -3,  1])

In [31]:
arr = np.arange(25)

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [34]:
ranar = np.random.randint(0,50,10)

In [35]:
ranar

array([29, 45, 32,  7, 23, 27, 28, 11, 44, 18])

In [36]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [38]:
ranar.max()

45

In [39]:
ranar.argmax()

1

In [40]:
arr.dtype

dtype('int64')

In [41]:
ranar.dtype

dtype('int64')