In [1]:
import numpy as np

In [5]:
arr = np.arange(0,11)

In [6]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr[5]

5

In [8]:
arr[1:6]

array([1, 2, 3, 4, 5])

In [9]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [10]:
arr[0:4] = 100

In [11]:
arr

array([100, 100, 100, 100,   4,   5,   6,   7,   8,   9,  10])

## para o numpy, slices dos arrays são apenas referências para o array original

In [20]:
arr = np.arange(0,11)

In [21]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
slice_of_arr = arr[0:6]

In [23]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [24]:
slice_of_arr[:] = 99

In [25]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [26]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## para criar cópias, precisamos definir explicitamente isso

In [27]:
arr_copy = arr.copy()

In [28]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [29]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [30]:
arr_copy[:] = 100

In [31]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [32]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## operaçoes com arrays de 2 dimensões

In [34]:
arr_2d = np.array([[5,10,15], [20,25,30], [35,40,45]])

In [35]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [37]:
arr_2d[0][1]

10

In [38]:
arr_2d[0]

array([ 5, 10, 15])

In [39]:
arr_2d[0,1]

10

In [40]:
arr_2d[2,2]

45

In [41]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [42]:
arr_2d[1:,:2]

array([[20, 25],
       [35, 40]])

## seleções condicionais

In [43]:
arr = np.arange(1,11)

In [44]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
bool_arr = arr > 5

In [46]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [47]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [49]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [50]:
arr[arr<3]

array([1, 2])

In [51]:
arr_2d = np.arange(1,51).reshape(5,10)

In [52]:
arr_2d

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [56]:
arr_2d[2:,6:]

array([[27, 28, 29, 30],
       [37, 38, 39, 40],
       [47, 48, 49, 50]])